quiz_index:
    resource: "@QuizIndexBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml

#oc_platform:
#    resource: "@OCPlatformBundle/Resources/config/routing.yml"
#    prefix:   /platform
login:
    path: /login
    defaults: { _controller: QuizIndexBundle:Quiz:connexion}

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout