# security:
#     providers:
#         in_memory:
#             memory: ~

#     firewalls:
#         dev:
#             pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#             security: false

#         default:
#             anonymous: ~

#         main:
#             pattern:   ^/
#             anonymous: true

# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Quiz\IndexBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Quiz\IndexBundle\Entity\User, property: username }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /index

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }