# quiz_index_homepage:
#     path:     /hello/{name}
#     defaults: { _controller: QuizIndexBundle:Default:index }

# hello_the_world:
#     path:     /hello-world
#     defaults: { _controller: QuizIndexBundle:Advert:index }

# bla_the_world:
#     path:     /bla/{id}/{bla}.{_format}
#     defaults: { _controller: QuizIndexBundle:Advert:bla, bla: 5555, _format: html  }
#     requirements:
#         id: \d*
#         bla: \d{4}
#         _format: html|xml|fr

# add_the_world:
#     path: /bla
#     defaults: { _controller: QuizIndexBundle:Advert:add}

inscription:
    path: /inscription
    defaults: { _controller: QuizIndexBundle:Quiz:inscription}

autre_page:
    path: /view
    defaults: { _controller: QuizIndexBundle:Quiz:view}

# login:
#     path: /login
#     defaults: { _controller: QuizIndexBundle:Quiz:connexion}

index2:
    path: /
    defaults: { _controller: QuizIndexBundle:Quiz:index}
index:
    path: /index
    defaults: { _controller: QuizIndexBundle:Quiz:index}

question:
    path: /question/{id}
    defaults: { _controller: QuizIndexBundle:Quiz:question}

add:
    path: /add
    defaults: { _controller: QuizIndexBundle:Quiz:addQuiz}

addC:
    path: /addC
    defaults: { _controller: QuizIndexBundle:Quiz:addC}

modif:
    path: /modif
    defaults: { _controller: QuizIndexBundle:Quiz:modif}
    # src/OC/PlatformBundle/Resources/config/routing.yml
    #prefix ajjouter ds app/config/routing.yml
#oc_platform_home:
#    path:      /
#    defaults:  { _controller: OCPlatformBundle:Advert:index }

#oc_platform_view:
#    path:      /advert/{id}
#    defaults:  { _controller: OCPlatformBundle:Advert:view }

#oc_platform_add:
#    path:      /add
#    defaults:  { _controller: OCPlatformBundle:Advert:add }

bla:
    path: /bla
    defaults: { _controller: QuizIndexBundle:Quiz:bla}